from pathlib import Path
from typing import Literal
from platformdirs import user_config_dir
import tomllib
import tomli_w
import inspect

class DefaultConfigError(Exception):
    pass

class ConfigHandler:
    def __init__(self):
        self.config_path = Path(user_config_dir("determinist", appauthor=False))
        self.presets_path = self.config_path / "presets"
        self.config_file = self.presets_path / "default.toml"

        self._initial_config()

    def _initial_config(self):
        is_first_run = not self.config_path.exists()
        self.presets_path.mkdir(parents=True, exist_ok=True)

        if is_first_run and not self.config_file.exists():
            default_config = """
            [preset]
            name = "Default"
            description = "The default preset generated by Determinist."
            is_default = true

            [general]
            version = 2
            pass_length = 8

            [v1]
            spec_mode = "insert"
            spec_freq = 4
            spec_chars = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
            char_map = {}

            [v2]
            char_types = ["special", "lowercase", "uppercase", "digits"]
            """

            default_config = inspect.cleandoc(default_config)
            self.config_file.write_text(default_config, encoding="utf-8")

    def get_files(self, mode: Literal["path", "name", "description", "default"]):
        details = []
        content = {}


        match mode:
            case "path":
                paths = []
                for file in self.presets_path.iterdir():
                    if file.is_file():
                        paths.append(file)
                return paths
            case "name":                
                for file in self.presets_path.iterdir():
                    content = self.load_config(file.name)
                    details.append((content["preset"]["name"]))
                return details
            case "description":
                for file in self.presets_path.iterdir():
                        content = self.load_config(file.name)
                        details.append((content["preset"]["description"]))
                return details
            case "default":
                for file in self.presets_path.iterdir():
                    content = self.load_config(file.name)

                    if content["preset"]["is_default"]:
                        details.append(content["preset"]["name"])
                return details


    def save_config(self, file: Path) -> None:
            target_path = self.presets_path / file.name
    
            file.copy(target_path)

    def load_config(self, file_name: str) -> dict:
        path = self.presets_path / file_name
        
        if path.suffix == "":
            path = self.presets_path / path.with_suffix(".toml")
        elif path.suffix == ".toml":
            pass

        with open(path, 'rb') as f:
            return tomllib.load(f)
        
    def delete_config(self, file_name: str, force: bool) -> None:
            target_path = self.presets_path / file_name

            content = {}
            if target_path.suffix == "":
                target_path = self.presets_path / target_path.with_suffix(".toml")
            elif target_path.suffix == ".toml":
                pass

            with open(target_path, 'rb') as f:
                content = tomllib.load(f)

            if content['preset']['is_default'] and force == False:
                raise DefaultConfigError(
                    f"Cannot delete '{target_path}' because it is set as the default configuration. "
                    "Please set another preset as default first or use --force."
                )
            else:
                target_path.unlink(missing_ok=True)
                print(f"Preset {file_name} deleted!")

    def get_default_path(self) -> Path | None:
        default_name = self.get_files("default")
        default_name = default_name[0] if default_name else None

        return next(
            (path for name, path in zip(self.get_files("name"), self.get_files("path")) if name == default_name),
            None
    )

    def set_default(self, file_name: str):
        target_path = self.presets_path / file_name
        current_default = self.get_default_path()
        assert current_default is not None
        
        content = {}
        if target_path.suffix == "":
            target_path = self.presets_path / target_path.with_suffix(".toml")
        elif target_path.suffix == ".toml":
            pass

        with open(target_path, 'rb') as f:
            content = tomllib.load(f)

        content["preset"]["is_default"] = True

        with open(target_path, 'wb') as f:
            tomli_w.dump(content, f)

        with open(current_default, 'rb') as f:
            content = tomllib.load(f)

        content["preset"]["is_default"] = False

        with open(current_default, 'wb') as f:
            tomli_w.dump(content, f)