from pathlib import Path
from platformdirs import user_config_dir
import tomllib
import inspect

class DefaultConfigError(Exception):
    pass

class ConfigHandler:
    def __init__(self):
        self.config_path = Path(user_config_dir("determinist", appauthor=False))
        self.presets_path = self.config_path / "presets"
        self.config_file = self.presets_path / "default.toml"

        self.config_path.mkdir(parents=True, exist_ok=True)
        self.presets_path.mkdir(parents=True, exist_ok=True)

        if not self.config_file.exists():
            default_config = """
            [preset]
            name = "Default"
            description = "The default preset generated by Determinist."
            is_default = true

            [general]
            version = 2
            pass_length = 8

            [v1]
            spec_mode = "insert"
            spec_freq = 4
            spec_chars = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
            char_map = {}

            [v2]
            char_types = ["special", "lowercase", "uppercase", "digits"]

            """
            default_config = inspect.cleandoc(default_config)
            self.config_file.write_text(default_config, encoding="utf-8")

    def save_config(self, file: Path) -> None:
            target_path = self.presets_path / file.name
    
            file.copy(target_path)

    def load_config(self, file_name: str) -> dict:
        path = self.config_path / file_name

        with open(path, 'rb') as f:
            return tomllib.load(f)
        
    def delete_config(self, file_name: str, force: bool) -> None:
            target_path = self.presets_path / file_name

            content = {}
            if target_path.suffix == "":
                target_path = self.presets_path / target_path.with_suffix(".toml")
            elif target_path.suffix == ".toml":
                pass

            with open(target_path, 'rb') as f:
                content = tomllib.load(f)

            if content['preset']['is_default'] and force == False:
                raise DefaultConfigError(
                    f"Cannot delete '{target_path}' because it is set as the default configuration. "
                    "Please set another preset as default first or use --force."
                )
            else:
                target_path.unlink(missing_ok=True)
                print(f"Preset {file_name} deleted!")