[project]
name = "determinist"
dynamic = ["version"]
description = "A deterministic password generator"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argon2-cffi>=25.1.0",
    "platformdirs>=4.11.0",
    "setuptools>=83.0.0",
    "setuptools-scm>=10.2.1",
    "tomli-w>=1.2.0",
    "typer>=0.27.0",
]

[project.scripts]
determinist = "determinist.generator:app"

[build-system]
requires = ["setuptools>=83.0.0", "setuptools_scm[toml]>=10.2.1"]
buuild-backend = "setuptools.build_meta"

[tool.uv.extra-build-dependencies]
determinist = ["setuptools"]

[tool.setuptools_scm]
root = ".."
write_to = "python/src/determinist/_version.py"
local_scheme = "no-local-version"